#!/usr/bin/env python3
"""
Live FreshCart event generator for M07 (Real-Time Intelligence) and M11 (Monitoring).
Emits one JSON event per second to stdout, and optionally POSTs each event to a
Fabric Eventstream custom endpoint URL. Stdlib only.

Event schema matches datasets/streaming/events_stream.jsonl (the static fallback
generated by ../generate_datasets.py):
    { "event_time": ISO-8601 UTC, "store_id": 1-5, "event_type": "scan"|"checkout"|"alert", "value": number }

Usage:
    python event_generator.py                                   # stdout only, runs until Ctrl+C
    python event_generator.py --count 50                        # stop after 50 events
    python event_generator.py --interval 0.5                    # emit twice a second
    python event_generator.py --endpoint https://<eventstream-custom-endpoint-url>
    python event_generator.py --seed 700                        # reproducible run (unseeded/live by default)
"""
import argparse
import json
import random
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone


def make_event(rng):
    event_type = rng.choices(["scan", "checkout", "alert"], weights=[60, 30, 10])[0]
    store_id = rng.randint(1, 5)
    if event_type == "scan":
        value = rng.randint(1, 4)              # items scanned
    elif event_type == "checkout":
        value = round(rng.uniform(8, 180), 2)   # sale amount ($)
    else:
        value = round(rng.uniform(45, 58), 1)   # freezer temp (°F) running warm -> the "alert"
    return {
        "event_time": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "store_id": store_id,
        "event_type": event_type,
        "value": value,
    }


def post_event(endpoint, event):
    data = json.dumps(event).encode("utf-8")
    req = urllib.request.Request(endpoint, data=data, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            return resp.status
    except urllib.error.URLError as e:
        print(f"  ⚠ POST to {endpoint} failed: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(description="Emit FreshCart events to stdout and/or a Fabric Eventstream endpoint.")
    parser.add_argument("--endpoint", help="Eventstream custom endpoint URL to POST each event to")
    parser.add_argument("--interval", type=float, default=1.0, help="Seconds between events (default: 1.0)")
    parser.add_argument("--count", type=int, default=None, help="Number of events to emit (default: run forever)")
    parser.add_argument("--seed", type=int, default=None, help="Random seed for a reproducible run (default: unseeded, i.e. live)")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    emitted = 0
    try:
        while args.count is None or emitted < args.count:
            event = make_event(rng)
            print(json.dumps(event), flush=True)
            if args.endpoint:
                post_event(args.endpoint, event)
            emitted += 1
            if args.count is None or emitted < args.count:
                time.sleep(args.interval)
    except KeyboardInterrupt:
        print(f"\nStopped after {emitted} events.", file=sys.stderr)


if __name__ == "__main__":
    main()
